{{- define "elastalert.config" }}
{{- if .Values.realertIntervalMins }}
realert:
  minutes: {{ .Values.realertIntervalMins }}
{{- end }}
rules_folder: /opt/elastalert/rules
# scan_subdirectories: false
run_every:
  minutes: {{ .Values.runIntervalMins }}
buffer_time:
  minutes: {{ .Values.bufferTimeMins }}
es_host: {{ .Values.elasticsearch.host }}
es_port: {{ .Values.elasticsearch.port }}
{{- if .Values.elasticsearch.username }}
es_username: {{ .Values.elasticsearch.username }}
{{- end }}
{{- if .Values.elasticsearch.password }}
es_password: {{ .Values.elasticsearch.password }}
{{- end }}
writeback_index: {{ .Values.writebackIndex }}
use_ssl: {{ .Values.elasticsearch.useSsl }}
verify_certs: {{ .Values.elasticsearch.verifyCerts }}
{{- if .Values.elasticsearch.clientCert }}
client_cert: {{ .Values.elasticsearch.clientCert }}
{{- end }}
{{- if .Values.elasticsearch.clientKey }}
client_key: {{ .Values.elasticsearch.clientKey }}
{{- end }}
{{- if .Values.elasticsearch.caCerts }}
ca_certs: {{ .Values.elasticsearch.caCerts }}
{{- end }}
alert_time_limit:
  minutes: {{ .Values.alertRetryLimitMins }}
{{- if .Values.extraConfigOptions }}
{{ toYaml .Values.extraConfigOptions }}
{{- end }}
{{- end }}



{{- define "elastalert.apiconfig" }}
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "{{ .Values.elasticsearch.host }}",
  "es_port": {{ .Values.elasticsearch.port }},
  "es_username": "{{ .Values.elasticsearch.username }}",
  "es_password": "{{ .Values.elasticsearch.password }}",
  "es_ssl": {{ .Values.elasticsearch.useSsl }},
  {{- if .Values.elasticsearch.verifyCerts }}
  "es_ca_certs": {{ .Values.elasticsearch.caCerts | quote }}, 
  {{- end }}
  "writeback_index": "{{ .Values.writebackIndex }}"
}
{{- end }}


{{- define "elastalert.rules_immutable" }}
{{- if .Values.rules_immutable }}755{{- else }}777{{- end }}
{{- end }}
