apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elastalert.fullname" . }}-rules
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Additional Rules provided by '.Values.rules'    
{{- range $key, $value := .Values.rules }}
{{ $key | indent 2 }}: {{ $value | b64enc }}
{{- end }}
