#Ref: https://github.com/helm/charts/blob/master/stable/elastalert/templates/config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elastalert.fullname" . }}-config
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  elastalert_config: |-
    {{ include "elastalert.config" . | b64enc }}

  elastalert_api_config: |-
    {{ include "elastalert.apiconfig" . | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "elastalert.fullname" . }}-baserule-config
  labels:
    app: {{ template "elastalert.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  baserule_config: |-
    {{ .Values.baserule | b64enc }}